# numpy

## Linear Algebra 

虽然强大的深度学习框架可以减少很多重复性工作，但如果你过于依赖它提供的便利抽象，那么你可能不会很容易地理解到底深度学习是如何工作的。所以我们的第一个教程是如何只利用ndarray和autograd来实现一个线性回归的训练。

import numpy as np

a = np.array([[1,2],[3,4]])

#矩阵转置
a.transpose()

In [4]:
#矩阵的逆
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#单位矩阵
# unit 2x2 matrix; "eye" represents "I"
u = np.eye(2)
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [5]:
#matrix product
#矩阵的乘积
j = np.array([[0,-1],[1,0]])
np.dot(j,j)

array([[-1,  0],
       [ 0, -1]])

In [8]:
#Return the sum along diagonals of the array
#对角线之和
np.trace(u)

2.0

In [14]:
y = np.array([[5.], [7.]])
#Solve a linear matrix equation
#解线性方程组
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [15]:
#Compute the eigenvalues and right eigenvectors of a square array
#计算方阵特征值
np.linalg.eig(j)

(array([ 0.+1.j,  0.-1.j]),
 array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))